### ISSUE TITLE
insert a feature

### ISSUE THREAD

**Issue by kttary** [ngageoint/geopackage-ios#39]
Hi, i'm very new to geopackage. Pls help me how to insert a feature on geopackage ios. Thing i've done so far:

```
let featureTables : NSArray = geoPackage.getFeatureTables() as NSArray;
let featureName: String = featureTables.object(at: featureTables.index(of: "Parks")) as! String;
let featureTable: GPKGFeatureDao = geoPackage.getFeatureDao(withTableName: featureName);

let featureRow: GPKGFeatureRow = featureTable.newRow();
let geomData: GPKGGeometryData = GPKGGeometryData(srsId: 4326);

let polygon: SFPolygon = SFPolygon(hasZ: false, andHasM: false);

let myLineString: SFLineString = getLineString(points: [[-90,38],[-90.001,38.001],[-90.002,38],[-90,38]]);
polygon.addRing(myLineString);

geomData.geometry = polygon;
featureRow.setGeometry(geomData);

featureRow.setValueWithColumnName("name", andValue: "test" as NSObject);
let tes: Int64 = featureTable.insert(featureRow);
print(tes);
```

and getLineString function

```
func getLineString(points: [[Decimal]] ) -> SFLineString {
        let lineString: SFLineString = SFLineString(hasZ: false, andHasM: false);
        for i in 0...points.count-1
        {
            let point: SFPoint = SFPoint(hasZ: false, andHasM: false, andX: points[i][0] as NSDecimalNumber, andY: points[i][1] as NSDecimalNumber);//(false, false, points[i][0], points[i][1]);
            lineString.addPoint(point);
        }
        return lineString;
    }
```

there is no error generated from my code but also no record inserted. Pls let me know how to fix the code. thank you in advance

**Comment by bosborn** [comment]
I pasted your code into the [Swift example at line 31](https://github.com/ngageoint/geopackage-ios/blob/7b139ada1f9f34881a8cb8952cbd507b1e09d4f6/docs/examples/swift/GeoPackage-to-go-iOS/GeoPackage-iOS-example/ViewController.swift#L31).  Everything compiled and ran OK.  The polygon could be seen on the map after panning to it (shown in this screenshot).

![simulator screen shot - iphone 8 plus - 2018-07-10 at 09 41 18](https://user-images.githubusercontent.com/11667761/42517723-ff37437e-8425-11e8-93a6-e8e60a979349.png)

**Comment by bosborn** [comment]
The edited GeoPackage will either exist on your simulator or your iOS device.  The original GeoPackage that was copied to the simulator/device is not modified.  Since it appears you are using a simulator, you can simply find the GeoPackage on your file system.  Look at the Xcode log output for the path which should be something like:
`/Users/<username>/Library/Developer/CoreSimulator/Devices/<device_id>/data/Containers/Data/Application/<application_id>/Documents/geopackage/db/StLouis.gpkg`
If you were using a device, you'd need to pull it from that device or export/share from the application.

<img width="1144" alt="screen shot 2018-07-11 at 6 48 51 am" src="https://user-images.githubusercontent.com/11667761/42572724-529f3146-84d7-11e8-95b0-806390e687c4.png">

**Comment by kttary** [comment]
Got it. Bunch of thanks!
